spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com.wujie: debug
    web: debug


mybatis:
  type-aliases-package: com.wujie.pojo
#  configuration:
#    lazy-loading-enabled: true


pagehelper:
  helper-dialect: mysql
  reasonable: true
server:
  port: 8081
